//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.tannguyen.com/types/", ClrNamespace="www.tannguyen.com.types")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.yourcompany.com/types/", ClrNamespace="www.yourcompany.com.types")]

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace www.tannguyen.com.types
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.tannguyen.com/types/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.tannguyen.com.types.LoginRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.tannguyen.com.types.LogoutRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.tannguyen.com.types.MapImageRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.yourcompany.com.types.TokenRequest))]
    public partial class RequestBase : object
    {
        
        private string AccessTokenField;
        
        private string ActionField;
        
        private string ClientTagField;
        
        private string[] LoadOptionsField;
        
        private string RequestIdField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTag
        {
            get
            {
                return this.ClientTagField;
            }
            set
            {
                this.ClientTagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LoadOptions
        {
            get
            {
                return this.LoadOptionsField;
            }
            set
            {
                this.LoadOptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://www.tannguyen.com/types/")]
    public partial class LoginRequest : www.tannguyen.com.types.RequestBase
    {
        
        private string PasswordField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutRequest", Namespace="http://www.tannguyen.com/types/")]
    public partial class LogoutRequest : www.tannguyen.com.types.RequestBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapImageRequest", Namespace="http://www.tannguyen.com/types/")]
    public partial class MapImageRequest : www.tannguyen.com.types.RequestBase
    {
        
        private www.tannguyen.com.types.MapImageDTO mapImageDTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.tannguyen.com.types.MapImageDTO mapImageDTO
        {
            get
            {
                return this.mapImageDTOField;
            }
            set
            {
                this.mapImageDTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapImageDTO", Namespace="http://www.tannguyen.com/types/")]
    public partial class MapImageDTO : object
    {
        
        private byte[] BitmapMapsStreamField;
        
        private string GetMakerField;
        
        private int HeightField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private int WidthField;
        
        private int ZoomField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BitmapMapsStream
        {
            get
            {
                return this.BitmapMapsStreamField;
            }
            set
            {
                this.BitmapMapsStreamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetMaker
        {
            get
            {
                return this.GetMakerField;
            }
            set
            {
                this.GetMakerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Zoom
        {
            get
            {
                return this.ZoomField;
            }
            set
            {
                this.ZoomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.tannguyen.com/types/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.tannguyen.com.types.LoginResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.tannguyen.com.types.LogoutResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.tannguyen.com.types.MapImageResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(www.yourcompany.com.types.TokenResponse))]
    public partial class ResponseBase : object
    {
        
        private www.tannguyen.com.types.AcknowledgeType AcknowledgeField;
        
        private string BuildField;
        
        private string CorrelationIdField;
        
        private string MessageField;
        
        private System.DateTime ReservationExpiresField;
        
        private string ReservationIdField;
        
        private int RowsAffectedField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.tannguyen.com.types.AcknowledgeType Acknowledge
        {
            get
            {
                return this.AcknowledgeField;
            }
            set
            {
                this.AcknowledgeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Build
        {
            get
            {
                return this.BuildField;
            }
            set
            {
                this.BuildField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId
        {
            get
            {
                return this.CorrelationIdField;
            }
            set
            {
                this.CorrelationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationExpires
        {
            get
            {
                return this.ReservationExpiresField;
            }
            set
            {
                this.ReservationExpiresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationId
        {
            get
            {
                return this.ReservationIdField;
            }
            set
            {
                this.ReservationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsAffected
        {
            get
            {
                return this.RowsAffectedField;
            }
            set
            {
                this.RowsAffectedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://www.tannguyen.com/types/")]
    public partial class LoginResponse : www.tannguyen.com.types.ResponseBase
    {
        
        private string SessionIdField;
        
        private string UriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId
        {
            get
            {
                return this.SessionIdField;
            }
            set
            {
                this.SessionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri
        {
            get
            {
                return this.UriField;
            }
            set
            {
                this.UriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutResponse", Namespace="http://www.tannguyen.com/types/")]
    public partial class LogoutResponse : www.tannguyen.com.types.ResponseBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapImageResponse", Namespace="http://www.tannguyen.com/types/")]
    public partial class MapImageResponse : www.tannguyen.com.types.ResponseBase
    {
        
        private www.tannguyen.com.types.MapImageDTO mapImageDTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public www.tannguyen.com.types.MapImageDTO mapImageDTO
        {
            get
            {
                return this.mapImageDTOField;
            }
            set
            {
                this.mapImageDTOField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeType", Namespace="http://www.tannguyen.com/types/")]
    public enum AcknowledgeType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
}
namespace www.yourcompany.com.types
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenRequest", Namespace="http://www.yourcompany.com/types/")]
    public partial class TokenRequest : www.tannguyen.com.types.RequestBase
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenResponse", Namespace="http://www.yourcompany.com/types/")]
    public partial class TokenResponse : www.tannguyen.com.types.ResponseBase
    {
        
        private string AccessTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken
        {
            get
            {
                return this.AccessTokenField;
            }
            set
            {
                this.AccessTokenField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMainService")]
public interface IMainService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMainService/GetToken", ReplyAction="http://tempuri.org/IMainService/GetTokenResponse")]
    System.IAsyncResult BeginGetToken(www.yourcompany.com.types.TokenRequest request, System.AsyncCallback callback, object asyncState);
    
    www.yourcompany.com.types.TokenResponse EndGetToken(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMainService/Login", ReplyAction="http://tempuri.org/IMainService/LoginResponse")]
    System.IAsyncResult BeginLogin(www.tannguyen.com.types.LoginRequest request, System.AsyncCallback callback, object asyncState);
    
    www.tannguyen.com.types.LoginResponse EndLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMainService/Logout", ReplyAction="http://tempuri.org/IMainService/LogoutResponse")]
    System.IAsyncResult BeginLogout(www.tannguyen.com.types.LogoutRequest request, System.AsyncCallback callback, object asyncState);
    
    www.tannguyen.com.types.LogoutResponse EndLogout(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMainService/GetMapGoogle", ReplyAction="http://tempuri.org/IMainService/GetMapGoogleResponse")]
    System.IAsyncResult BeginGetMapGoogle(www.tannguyen.com.types.MapImageRequest request, System.AsyncCallback callback, object asyncState);
    
    www.tannguyen.com.types.MapImageResponse EndGetMapGoogle(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMainServiceChannel : IMainService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public www.yourcompany.com.types.TokenResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((www.yourcompany.com.types.TokenResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public www.tannguyen.com.types.LoginResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((www.tannguyen.com.types.LoginResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public www.tannguyen.com.types.LogoutResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((www.tannguyen.com.types.LogoutResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetMapGoogleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetMapGoogleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public www.tannguyen.com.types.MapImageResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((www.tannguyen.com.types.MapImageResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MainServiceClient : System.ServiceModel.ClientBase<IMainService>, IMainService
{
    
    private BeginOperationDelegate onBeginGetTokenDelegate;
    
    private EndOperationDelegate onEndGetTokenDelegate;
    
    private System.Threading.SendOrPostCallback onGetTokenCompletedDelegate;
    
    private BeginOperationDelegate onBeginLoginDelegate;
    
    private EndOperationDelegate onEndLoginDelegate;
    
    private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
    
    private BeginOperationDelegate onBeginLogoutDelegate;
    
    private EndOperationDelegate onEndLogoutDelegate;
    
    private System.Threading.SendOrPostCallback onLogoutCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetMapGoogleDelegate;
    
    private EndOperationDelegate onEndGetMapGoogleDelegate;
    
    private System.Threading.SendOrPostCallback onGetMapGoogleCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public MainServiceClient()
    {
    }
    
    public MainServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MainServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetTokenCompletedEventArgs> GetTokenCompleted;
    
    public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
    
    public event System.EventHandler<LogoutCompletedEventArgs> LogoutCompleted;
    
    public event System.EventHandler<GetMapGoogleCompletedEventArgs> GetMapGoogleCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMainService.BeginGetToken(www.yourcompany.com.types.TokenRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetToken(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    www.yourcompany.com.types.TokenResponse IMainService.EndGetToken(System.IAsyncResult result)
    {
        return base.Channel.EndGetToken(result);
    }
    
    private System.IAsyncResult OnBeginGetToken(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        www.yourcompany.com.types.TokenRequest request = ((www.yourcompany.com.types.TokenRequest)(inValues[0]));
        return ((IMainService)(this)).BeginGetToken(request, callback, asyncState);
    }
    
    private object[] OnEndGetToken(System.IAsyncResult result)
    {
        www.yourcompany.com.types.TokenResponse retVal = ((IMainService)(this)).EndGetToken(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetTokenCompleted(object state)
    {
        if ((this.GetTokenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetTokenCompleted(this, new GetTokenCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetTokenAsync(www.yourcompany.com.types.TokenRequest request)
    {
        this.GetTokenAsync(request, null);
    }
    
    public void GetTokenAsync(www.yourcompany.com.types.TokenRequest request, object userState)
    {
        if ((this.onBeginGetTokenDelegate == null))
        {
            this.onBeginGetTokenDelegate = new BeginOperationDelegate(this.OnBeginGetToken);
        }
        if ((this.onEndGetTokenDelegate == null))
        {
            this.onEndGetTokenDelegate = new EndOperationDelegate(this.OnEndGetToken);
        }
        if ((this.onGetTokenCompletedDelegate == null))
        {
            this.onGetTokenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTokenCompleted);
        }
        base.InvokeAsync(this.onBeginGetTokenDelegate, new object[] {
                    request}, this.onEndGetTokenDelegate, this.onGetTokenCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMainService.BeginLogin(www.tannguyen.com.types.LoginRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginLogin(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    www.tannguyen.com.types.LoginResponse IMainService.EndLogin(System.IAsyncResult result)
    {
        return base.Channel.EndLogin(result);
    }
    
    private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        www.tannguyen.com.types.LoginRequest request = ((www.tannguyen.com.types.LoginRequest)(inValues[0]));
        return ((IMainService)(this)).BeginLogin(request, callback, asyncState);
    }
    
    private object[] OnEndLogin(System.IAsyncResult result)
    {
        www.tannguyen.com.types.LoginResponse retVal = ((IMainService)(this)).EndLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnLoginCompleted(object state)
    {
        if ((this.LoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void LoginAsync(www.tannguyen.com.types.LoginRequest request)
    {
        this.LoginAsync(request, null);
    }
    
    public void LoginAsync(www.tannguyen.com.types.LoginRequest request, object userState)
    {
        if ((this.onBeginLoginDelegate == null))
        {
            this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
        }
        if ((this.onEndLoginDelegate == null))
        {
            this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
        }
        if ((this.onLoginCompletedDelegate == null))
        {
            this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
        }
        base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                    request}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMainService.BeginLogout(www.tannguyen.com.types.LogoutRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginLogout(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    www.tannguyen.com.types.LogoutResponse IMainService.EndLogout(System.IAsyncResult result)
    {
        return base.Channel.EndLogout(result);
    }
    
    private System.IAsyncResult OnBeginLogout(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        www.tannguyen.com.types.LogoutRequest request = ((www.tannguyen.com.types.LogoutRequest)(inValues[0]));
        return ((IMainService)(this)).BeginLogout(request, callback, asyncState);
    }
    
    private object[] OnEndLogout(System.IAsyncResult result)
    {
        www.tannguyen.com.types.LogoutResponse retVal = ((IMainService)(this)).EndLogout(result);
        return new object[] {
                retVal};
    }
    
    private void OnLogoutCompleted(object state)
    {
        if ((this.LogoutCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.LogoutCompleted(this, new LogoutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void LogoutAsync(www.tannguyen.com.types.LogoutRequest request)
    {
        this.LogoutAsync(request, null);
    }
    
    public void LogoutAsync(www.tannguyen.com.types.LogoutRequest request, object userState)
    {
        if ((this.onBeginLogoutDelegate == null))
        {
            this.onBeginLogoutDelegate = new BeginOperationDelegate(this.OnBeginLogout);
        }
        if ((this.onEndLogoutDelegate == null))
        {
            this.onEndLogoutDelegate = new EndOperationDelegate(this.OnEndLogout);
        }
        if ((this.onLogoutCompletedDelegate == null))
        {
            this.onLogoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogoutCompleted);
        }
        base.InvokeAsync(this.onBeginLogoutDelegate, new object[] {
                    request}, this.onEndLogoutDelegate, this.onLogoutCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMainService.BeginGetMapGoogle(www.tannguyen.com.types.MapImageRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetMapGoogle(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    www.tannguyen.com.types.MapImageResponse IMainService.EndGetMapGoogle(System.IAsyncResult result)
    {
        return base.Channel.EndGetMapGoogle(result);
    }
    
    private System.IAsyncResult OnBeginGetMapGoogle(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        www.tannguyen.com.types.MapImageRequest request = ((www.tannguyen.com.types.MapImageRequest)(inValues[0]));
        return ((IMainService)(this)).BeginGetMapGoogle(request, callback, asyncState);
    }
    
    private object[] OnEndGetMapGoogle(System.IAsyncResult result)
    {
        www.tannguyen.com.types.MapImageResponse retVal = ((IMainService)(this)).EndGetMapGoogle(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetMapGoogleCompleted(object state)
    {
        if ((this.GetMapGoogleCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetMapGoogleCompleted(this, new GetMapGoogleCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetMapGoogleAsync(www.tannguyen.com.types.MapImageRequest request)
    {
        this.GetMapGoogleAsync(request, null);
    }
    
    public void GetMapGoogleAsync(www.tannguyen.com.types.MapImageRequest request, object userState)
    {
        if ((this.onBeginGetMapGoogleDelegate == null))
        {
            this.onBeginGetMapGoogleDelegate = new BeginOperationDelegate(this.OnBeginGetMapGoogle);
        }
        if ((this.onEndGetMapGoogleDelegate == null))
        {
            this.onEndGetMapGoogleDelegate = new EndOperationDelegate(this.OnEndGetMapGoogle);
        }
        if ((this.onGetMapGoogleCompletedDelegate == null))
        {
            this.onGetMapGoogleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMapGoogleCompleted);
        }
        base.InvokeAsync(this.onBeginGetMapGoogleDelegate, new object[] {
                    request}, this.onEndGetMapGoogleDelegate, this.onGetMapGoogleCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IMainService CreateChannel()
    {
        return new MainServiceClientChannel(this);
    }
    
    private class MainServiceClientChannel : ChannelBase<IMainService>, IMainService
    {
        
        public MainServiceClientChannel(System.ServiceModel.ClientBase<IMainService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetToken(www.yourcompany.com.types.TokenRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetToken", _args, callback, asyncState);
            return _result;
        }
        
        public www.yourcompany.com.types.TokenResponse EndGetToken(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            www.yourcompany.com.types.TokenResponse _result = ((www.yourcompany.com.types.TokenResponse)(base.EndInvoke("GetToken", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginLogin(www.tannguyen.com.types.LoginRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
            return _result;
        }
        
        public www.tannguyen.com.types.LoginResponse EndLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            www.tannguyen.com.types.LoginResponse _result = ((www.tannguyen.com.types.LoginResponse)(base.EndInvoke("Login", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginLogout(www.tannguyen.com.types.LogoutRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("Logout", _args, callback, asyncState);
            return _result;
        }
        
        public www.tannguyen.com.types.LogoutResponse EndLogout(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            www.tannguyen.com.types.LogoutResponse _result = ((www.tannguyen.com.types.LogoutResponse)(base.EndInvoke("Logout", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetMapGoogle(www.tannguyen.com.types.MapImageRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetMapGoogle", _args, callback, asyncState);
            return _result;
        }
        
        public www.tannguyen.com.types.MapImageResponse EndGetMapGoogle(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            www.tannguyen.com.types.MapImageResponse _result = ((www.tannguyen.com.types.MapImageResponse)(base.EndInvoke("GetMapGoogle", _args, result)));
            return _result;
        }
    }
}
