//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace WcfService1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaceObjectViewData", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class PlaceObjectViewData : object
    {
        
        private string AddressField;
        
        private string ArticleField;
        
        private string ContentField;
        
        private System.Nullable<System.DateTime> DatePostField;
        
        private string IconField;
        
        private string IdObjectField;
        
        private byte[] ImageUrlField;
        
        private System.Nullable<bool> IsFavoriteField;
        
        private string LinkYoutubeField;
        
        private WcfService1.ItemComment[] ListCommentField;
        
        private string NameAuthorField;
        
        private System.Nullable<int> RatingLevelField;
        
        private string ShorDescriptionField;
        
        private string TitleField;
        
        private double ZoomLevelField;
        
        private string backgroundField;
        
        private System.Nullable<bool> isFavorite1Field;
        
        private System.Nullable<double> lattitudeField;
        
        private byte[][] listImageField;
        
        private System.Nullable<double> longtitudeField;
        
        private int ratingLevel1Field;
        
        private string title1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Article
        {
            get
            {
                return this.ArticleField;
            }
            set
            {
                this.ArticleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatePost
        {
            get
            {
                return this.DatePostField;
            }
            set
            {
                this.DatePostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icon
        {
            get
            {
                return this.IconField;
            }
            set
            {
                this.IconField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdObject
        {
            get
            {
                return this.IdObjectField;
            }
            set
            {
                this.IdObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFavorite
        {
            get
            {
                return this.IsFavoriteField;
            }
            set
            {
                this.IsFavoriteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkYoutube
        {
            get
            {
                return this.LinkYoutubeField;
            }
            set
            {
                this.LinkYoutubeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfService1.ItemComment[] ListComment
        {
            get
            {
                return this.ListCommentField;
            }
            set
            {
                this.ListCommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAuthor
        {
            get
            {
                return this.NameAuthorField;
            }
            set
            {
                this.NameAuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RatingLevel
        {
            get
            {
                return this.RatingLevelField;
            }
            set
            {
                this.RatingLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShorDescription
        {
            get
            {
                return this.ShorDescriptionField;
            }
            set
            {
                this.ShorDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ZoomLevel
        {
            get
            {
                return this.ZoomLevelField;
            }
            set
            {
                this.ZoomLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string background
        {
            get
            {
                return this.backgroundField;
            }
            set
            {
                this.backgroundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="isFavorite")]
        public System.Nullable<bool> isFavorite1
        {
            get
            {
                return this.isFavorite1Field;
            }
            set
            {
                this.isFavorite1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> lattitude
        {
            get
            {
                return this.lattitudeField;
            }
            set
            {
                this.lattitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] listImage
        {
            get
            {
                return this.listImageField;
            }
            set
            {
                this.listImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> longtitude
        {
            get
            {
                return this.longtitudeField;
            }
            set
            {
                this.longtitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ratingLevel")]
        public int ratingLevel1
        {
            get
            {
                return this.ratingLevel1Field;
            }
            set
            {
                this.ratingLevel1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="title")]
        public string title1
        {
            get
            {
                return this.title1Field;
            }
            set
            {
                this.title1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemComment", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class ItemComment : object
    {
        
        private string AuthorField;
        
        private string CommentStringField;
        
        private System.Nullable<System.DateTime> DataPostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentString
        {
            get
            {
                return this.CommentStringField;
            }
            set
            {
                this.CommentStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataPost
        {
            get
            {
                return this.DataPostField;
            }
            set
            {
                this.DataPostField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService1")]
public interface IService1
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
    System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
    
    string EndGetData(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
    System.IAsyncResult BeginGetDataUsingDataContract(WcfService1.CompositeType composite, System.AsyncCallback callback, object asyncState);
    
    WcfService1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetTenItems", ReplyAction="http://tempuri.org/IService1/GetTenItemsResponse")]
    System.IAsyncResult BeginGetTenItems(System.AsyncCallback callback, object asyncState);
    
    WcfService1.PlaceObjectViewData[] EndGetTenItems(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UpdatePlaceObjectComments", ReplyAction="http://tempuri.org/IService1/UpdatePlaceObjectCommentsResponse")]
    System.IAsyncResult BeginUpdatePlaceObjectComments(int id, WcfService1.ItemComment comment, System.AsyncCallback callback, object asyncState);
    
    bool EndUpdatePlaceObjectComments(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfService1.CompositeType Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfService1.CompositeType)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetTenItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetTenItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public WcfService1.PlaceObjectViewData[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((WcfService1.PlaceObjectViewData[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class UpdatePlaceObjectCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public UpdatePlaceObjectCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{
    
    private BeginOperationDelegate onBeginGetDataDelegate;
    
    private EndOperationDelegate onEndGetDataDelegate;
    
    private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
    
    private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
    
    private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetTenItemsDelegate;
    
    private EndOperationDelegate onEndGetTenItemsDelegate;
    
    private System.Threading.SendOrPostCallback onGetTenItemsCompletedDelegate;
    
    private BeginOperationDelegate onBeginUpdatePlaceObjectCommentsDelegate;
    
    private EndOperationDelegate onEndUpdatePlaceObjectCommentsDelegate;
    
    private System.Threading.SendOrPostCallback onUpdatePlaceObjectCommentsCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public Service1Client()
    {
    }
    
    public Service1Client(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public Service1Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
    
    public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
    
    public event System.EventHandler<GetTenItemsCompletedEventArgs> GetTenItemsCompleted;
    
    public event System.EventHandler<UpdatePlaceObjectCommentsCompletedEventArgs> UpdatePlaceObjectCommentsCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetData(int value, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetData(value, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IService1.EndGetData(System.IAsyncResult result)
    {
        return base.Channel.EndGetData(result);
    }
    
    private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int value = ((int)(inValues[0]));
        return ((IService1)(this)).BeginGetData(value, callback, asyncState);
    }
    
    private object[] OnEndGetData(System.IAsyncResult result)
    {
        string retVal = ((IService1)(this)).EndGetData(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetDataCompleted(object state)
    {
        if ((this.GetDataCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetDataAsync(int value)
    {
        this.GetDataAsync(value, null);
    }
    
    public void GetDataAsync(int value, object userState)
    {
        if ((this.onBeginGetDataDelegate == null))
        {
            this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
        }
        if ((this.onEndGetDataDelegate == null))
        {
            this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
        }
        if ((this.onGetDataCompletedDelegate == null))
        {
            this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
        }
        base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                    value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetDataUsingDataContract(WcfService1.CompositeType composite, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfService1.CompositeType IService1.EndGetDataUsingDataContract(System.IAsyncResult result)
    {
        return base.Channel.EndGetDataUsingDataContract(result);
    }
    
    private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        WcfService1.CompositeType composite = ((WcfService1.CompositeType)(inValues[0]));
        return ((IService1)(this)).BeginGetDataUsingDataContract(composite, callback, asyncState);
    }
    
    private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result)
    {
        WcfService1.CompositeType retVal = ((IService1)(this)).EndGetDataUsingDataContract(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetDataUsingDataContractCompleted(object state)
    {
        if ((this.GetDataUsingDataContractCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetDataUsingDataContractAsync(WcfService1.CompositeType composite)
    {
        this.GetDataUsingDataContractAsync(composite, null);
    }
    
    public void GetDataUsingDataContractAsync(WcfService1.CompositeType composite, object userState)
    {
        if ((this.onBeginGetDataUsingDataContractDelegate == null))
        {
            this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
        }
        if ((this.onEndGetDataUsingDataContractDelegate == null))
        {
            this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
        }
        if ((this.onGetDataUsingDataContractCompletedDelegate == null))
        {
            this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
        }
        base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                    composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginGetTenItems(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetTenItems(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    WcfService1.PlaceObjectViewData[] IService1.EndGetTenItems(System.IAsyncResult result)
    {
        return base.Channel.EndGetTenItems(result);
    }
    
    private System.IAsyncResult OnBeginGetTenItems(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IService1)(this)).BeginGetTenItems(callback, asyncState);
    }
    
    private object[] OnEndGetTenItems(System.IAsyncResult result)
    {
        WcfService1.PlaceObjectViewData[] retVal = ((IService1)(this)).EndGetTenItems(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetTenItemsCompleted(object state)
    {
        if ((this.GetTenItemsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetTenItemsCompleted(this, new GetTenItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetTenItemsAsync()
    {
        this.GetTenItemsAsync(null);
    }
    
    public void GetTenItemsAsync(object userState)
    {
        if ((this.onBeginGetTenItemsDelegate == null))
        {
            this.onBeginGetTenItemsDelegate = new BeginOperationDelegate(this.OnBeginGetTenItems);
        }
        if ((this.onEndGetTenItemsDelegate == null))
        {
            this.onEndGetTenItemsDelegate = new EndOperationDelegate(this.OnEndGetTenItems);
        }
        if ((this.onGetTenItemsCompletedDelegate == null))
        {
            this.onGetTenItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTenItemsCompleted);
        }
        base.InvokeAsync(this.onBeginGetTenItemsDelegate, null, this.onEndGetTenItemsDelegate, this.onGetTenItemsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IService1.BeginUpdatePlaceObjectComments(int id, WcfService1.ItemComment comment, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginUpdatePlaceObjectComments(id, comment, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IService1.EndUpdatePlaceObjectComments(System.IAsyncResult result)
    {
        return base.Channel.EndUpdatePlaceObjectComments(result);
    }
    
    private System.IAsyncResult OnBeginUpdatePlaceObjectComments(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int id = ((int)(inValues[0]));
        WcfService1.ItemComment comment = ((WcfService1.ItemComment)(inValues[1]));
        return ((IService1)(this)).BeginUpdatePlaceObjectComments(id, comment, callback, asyncState);
    }
    
    private object[] OnEndUpdatePlaceObjectComments(System.IAsyncResult result)
    {
        bool retVal = ((IService1)(this)).EndUpdatePlaceObjectComments(result);
        return new object[] {
                retVal};
    }
    
    private void OnUpdatePlaceObjectCommentsCompleted(object state)
    {
        if ((this.UpdatePlaceObjectCommentsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.UpdatePlaceObjectCommentsCompleted(this, new UpdatePlaceObjectCommentsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void UpdatePlaceObjectCommentsAsync(int id, WcfService1.ItemComment comment)
    {
        this.UpdatePlaceObjectCommentsAsync(id, comment, null);
    }
    
    public void UpdatePlaceObjectCommentsAsync(int id, WcfService1.ItemComment comment, object userState)
    {
        if ((this.onBeginUpdatePlaceObjectCommentsDelegate == null))
        {
            this.onBeginUpdatePlaceObjectCommentsDelegate = new BeginOperationDelegate(this.OnBeginUpdatePlaceObjectComments);
        }
        if ((this.onEndUpdatePlaceObjectCommentsDelegate == null))
        {
            this.onEndUpdatePlaceObjectCommentsDelegate = new EndOperationDelegate(this.OnEndUpdatePlaceObjectComments);
        }
        if ((this.onUpdatePlaceObjectCommentsCompletedDelegate == null))
        {
            this.onUpdatePlaceObjectCommentsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePlaceObjectCommentsCompleted);
        }
        base.InvokeAsync(this.onBeginUpdatePlaceObjectCommentsDelegate, new object[] {
                    id,
                    comment}, this.onEndUpdatePlaceObjectCommentsDelegate, this.onUpdatePlaceObjectCommentsCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IService1 CreateChannel()
    {
        return new Service1ClientChannel(this);
    }
    
    private class Service1ClientChannel : ChannelBase<IService1>, IService1
    {
        
        public Service1ClientChannel(System.ServiceModel.ClientBase<IService1> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = value;
            System.IAsyncResult _result = base.BeginInvoke("GetData", _args, callback, asyncState);
            return _result;
        }
        
        public string EndGetData(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("GetData", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetDataUsingDataContract(WcfService1.CompositeType composite, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = composite;
            System.IAsyncResult _result = base.BeginInvoke("GetDataUsingDataContract", _args, callback, asyncState);
            return _result;
        }
        
        public WcfService1.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfService1.CompositeType _result = ((WcfService1.CompositeType)(base.EndInvoke("GetDataUsingDataContract", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetTenItems(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("GetTenItems", _args, callback, asyncState);
            return _result;
        }
        
        public WcfService1.PlaceObjectViewData[] EndGetTenItems(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            WcfService1.PlaceObjectViewData[] _result = ((WcfService1.PlaceObjectViewData[])(base.EndInvoke("GetTenItems", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginUpdatePlaceObjectComments(int id, WcfService1.ItemComment comment, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = comment;
            System.IAsyncResult _result = base.BeginInvoke("UpdatePlaceObjectComments", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndUpdatePlaceObjectComments(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("UpdatePlaceObjectComments", _args, result)));
            return _result;
        }
    }
}
